### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by aaron4444** [xpdAcq/xpdtools#26] opened 2018-03-13 01:34 UTC
when trying to install with conda forge, it says:
that the package is not available, even though conda-forge is my first channel. 

Building from source was fine. 

![conda](https://user-images.githubusercontent.com/20306451/37317524-b6379a54-263b-11e8-8edf-2cf8d59240b4.PNG)

**Comment by CJ-Wright** [comment] 2018-03-13 02:15
Sorry! Thank you for reporting 
The issue is pyFAI doesn't currently have a conda recipe which builds on windows.

**Comment by CJ-Wright** [comment] 2018-05-03 16:27
pyFAI now has a windows build so I'm going to close this. Please feel free to reopen if this is still an issue.

**Closed by CJ-Wright** 2018-05-03 16:27 UTC
